# development
version: "2.1"
services:
  mqtt-broker:
    build: ../../services/mqtt-broker
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ../../services/mqtt-broker:/mosquitto

  decision-maker:
    build: ../../services/decision-maker
    container_name: decision-maker
    volumes:
      - ../../services/decision-maker:/decision-maker

  time-slot-booking:
    build: ../../services/time-slot-booking
    container_name: time-slot-booking
    depends_on:
      - mqtt-broker
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ../../services/time-slot-booking:/app
    environment:
      - FLASK_ENV=development
      - MQTT_HOST=mqtt-broker
      - MAIL_USER=noreply.jarvil@gmail.com
      - MAIL_PASSWORD=Sitter-Luckiness-Legwarmer1-Wobbling

  time-slot-validation:
    build: ../../services/time-slot-validation
    container_name: time-slot-validation
    depends_on:
      - mqtt-broker
      - redis
    volumes:
      - ../../services/time-slot-validation:/app
    environment:
      - MQTT_HOST=mqtt-broker

  redis:
    image: redis:alpine
    container_name: redis
    
  redisinsight:
    image: 'redislabs/redisinsight'
    container_name: redisinsight
    ports:
        - '8001:8001'

  mqtt-client:
    build: ../../services/mqtt-client
    container_name: mqtt-client
    volumes:
      - ../../services/mqtt-client:/client
    links:
      - "influxdb"
    environment:
      - MQTT_HOST=mqtt-broker
      - ORG=jarvil
      - BUCKET=jarvil-bucket
      - TOKEN=V_g3T7i-QyHF3e_uDvBE05MRVKd-234xHwLDACXuw457UnhEBFOVP1Cr5IVb1EclrG6IRS5uBjMbOhMidnu8kA==

  control-dashboard:
    build: ../../services/control-dashboard
    container_name: control-dashboard
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../../services/control-dashboard:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_PANELS_DISABLE_SANITIZE_HTML=true

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=grafana
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=jarvil
      - DOCKER_INFLUXDB_INIT_BUCKET=jarvil-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=V_g3T7i-QyHF3e_uDvBE05MRVKd-234xHwLDACXuw457UnhEBFOVP1Cr5IVb1EclrG6IRS5uBjMbOhMidnu8kA==

volumes:
  grafana_data:
  influxdb_data:
  influxdb_config:

