# development
version: "2.1"
services:
  mqtt-broker:
    build: ../../src/mqtt-broker
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ../../src/mqtt-broker:/mosquitto

  time-slot-booking:
    build: ../../src/time-slot-booking
    container_name: time-slot-booking
    ports:
      - "5000:5000"
    volumes:
      - ../../src/time-slot-booking:/app
    environment:
      FLASK_ENV: development

  redis:
    image: redis:alpine
    container_name: redis
    
  redisinsight:
    image: 'redislabs/redisinsight'
    container_name: redisinsight
    ports:
        - '8001:8001'

