# development
version: "2.1"
services:
  mqtt-broker:
    build: ../../services/mqtt-broker
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ../../services/mqtt-broker:/mosquitto

  time-slot-booking:
    build: ../../services/time-slot-booking
    container_name: time-slot-booking
    depends_on:
      - "mqtt-broker"
      - "redis"
    ports:
      - "5000:5000"
    volumes:
      - ../../services/time-slot-booking:/app
    environment:
      - FLASK_ENV=development
      - MQTT_HOST=mqtt-broker
      - MAIL_USER=noreply.jarvil@gmail.com
      - MAIL_PASSWORD=Sitter-Luckiness-Legwarmer1-Wobbling

  time-slot-validation:
    build: ../../services/time-slot-validation
    container_name: time-slot-validation
    depends_on:
      - "mqtt-broker"
      - "redis"
    volumes:
      - ../../services/time-slot-validation:/app
    environment:
      - MQTT_HOST=mqtt-broker

  redis:
    image: redis:alpine
    container_name: redis
    
  redisinsight:
    image: 'redislabs/redisinsight'
    container_name: redisinsight
    ports:
        - '8001:8001'

  mqtt-client:
    build: ../../services/mqtt-client
    container_name: mqtt-client
    volumes:
      - ../../services/mqtt-client:/client
    links:
      - "influxdb"
    volumes:
      - ../../services/mqtt-client:/client
    environment:
      - MQTT_HOST=mqtt-broker
      - ORG=jarvil
      - BUCKET=jarvil-bucket
      - TOKEN=V_g3T7i-QyHF3e_uDvBE05MRVKd-234xHwLDACXuw457UnhEBFOVP1Cr5IVb1EclrG6IRS5uBjMbOhMidnu8kA==
    

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../../services/data/grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ../../services/data/influxdb_data:/var/lib/influxdb2
      - ../../services/data/influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=grafana
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=jarvil
      - DOCKER_INFLUXDB_INIT_BUCKET=jarvil-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=V_g3T7i-QyHF3e_uDvBE05MRVKd-234xHwLDACXuw457UnhEBFOVP1Cr5IVb1EclrG6IRS5uBjMbOhMidnu8kA==

volumes:
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local

