version: "2.1"
services:
  mqtt-broker:
    build: ./mqtt-broker
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
  time-slot-booking:
    build: ./time-slot-booking
    ports:
      - "5000:5000"
