version: "2.1"
services:
  mqtt-broker:
    build: ./mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt-broker:/mosquitto
  time-slot-booking:
    build: ./time-slot-booking
    ports:
      - "5000:5000"
    volumes:
      - ./time-slot-booking:/app
    environment:
      FLASK_ENV: development

