version: "3.9"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001