# time slot booking with redis cache
version: "2.1"
services:
    
  mqtt-broker:
    # root path due to github actions file copy
    build: ./services/mqtt-broker
    container_name: mqtt-broker
    restart: always
    ports:
      - 1883:1883
      - 9001:9001