# mqtt broker with influxdb and grafana
version: "2.1"
services:
  mqtt-broker:
    build: ../../src/mqtt-broker
    container_name: mqtt-broker
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    
  mqtt-client:
    build: ../../src/mqtt-client
    volumes:
      - ../../src/mqtt-client:/client
    links:
      - "influxdb"
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../../src/data/grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ../../src/data/influxdb_data:/var/lib/influxdb2
      - ../../src/data/influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=grafana
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=jarvil
      - DOCKER_INFLUXDB_INIT_BUCKET=jarvil-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=V_g3T7i-QyHF3e_uDvBE05MRVKd-234xHwLDACXuw457UnhEBFOVP1Cr5IVb1EclrG6IRS5uBjMbOhMidnu8kA==

volumes:
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local