# mqtt broker
version: "2.1"
services:
    
  mqtt-broker:
    # root path due to github actions file copy
    build: ./services/mqtt-broker
    container_name: mqtt-broker
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    
  decision-maker:
    build: ./services/decision-maker
    container_name: decision-maker
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker