# mqtt endpoint devices
version: "2.1"
services:

  brightness-service:
    # root path due to github actions file copy
    build: ./services/environment-service-pi
    volumes:
      - ./services/environment-service-pi:/app
    devices:
      - /dev/ttyACM0