# mqtt endpoint devices
version: "2.1"
services:

  climate-service:
    # root path due to github actions file copy
    build: ./services/climate-service-pi
    devices:
      - /dev/ttyACM0
    environment:
      - MQTT_HOST=mqtt-broker
      - USB_PORT=/dev/ttyACM0
      - BRIGHTNESS_PORT = 0