# mqtt endpoint devices
version: "2.1"
services:

  climate-service:
    # root path due to github actions file copy
    build: ./services/climate-service-pi
    privileged: true
    devices:
      - /dev/ttyACM0
    environment:
      - MQTT_HOST=mqtt-broker
      - USB_PORT=/dev/ttyACM0
      - BRIGHTNESS_PORT=0
      - AIRCONDITION_PORT=5
      - HUMIDITY_TEMPERATURE_PORT=23
      - LIGHT_PORT=8
      - AIRFILTER_PORT=9
      - HUMIDIFIER_PORT=10
      - THERMOSTAT_PORT=11

  door-service:
    # root path due to github actions file copy
    build: ./services/door-service
    devices:
      # TODO: check if it is so
      - /dev/ttyACM1
    environment:
      - MQTT_HOST=mqtt-broker
      - USB_PORT=/dev/ttyACM1
      - DOOR_PORT=2