# mqtt broker with influxdb and grafana
version: "2.1"
services:

  time-slot-booking:
    # root path due to github actions file copy
    build: ./services/time-slot-booking
    container_name: time-slot-booking
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - MQTT_HOST=mqtt-broker
      - MAIL_USER=noreply.jarvil@gmail.com
      - MAIL_PASSWORD=Sitter-Luckiness-Legwarmer1-Wobbling

  time-slot-validation:
    # root path due to github actions file copy
    build: ./services/time-slot-validation
    container_name: time-slot-validation
    depends_on:
      - redis
    devices:
      - /dev/video0
    environment:
      - MQTT_HOST=mqtt-broker

  redis:
    image: redis:alpine
    container_name: redis
    
  mqtt-client:
    # root path due to github actions file copy
    build: ./services/mqtt-client
    links:
      - "influxdb"
    environment:
      - MQTT_HOST=mqtt-broker
      - ORG=jarvil
      - BUCKET=jarvil-bucket
      - TOKEN=V_g3T7i-QyHF3e_uDvBE05MRVKd-234xHwLDACXuw457UnhEBFOVP1Cr5IVb1EclrG6IRS5uBjMbOhMidnu8kA==
  
  grafana:
    # root path due to github actions file copy
    build: ./services/control-dashboard
    container_name: control-dashboard
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=aidanmountford-html-panel

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=grafana
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=jarvil
      - DOCKER_INFLUXDB_INIT_BUCKET=jarvil-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=V_g3T7i-QyHF3e_uDvBE05MRVKd-234xHwLDACXuw457UnhEBFOVP1Cr5IVb1EclrG6IRS5uBjMbOhMidnu8kA==
