{
 "title": "Library Control",
 "description": "Dashboard to view real-time stats and control global library parameters",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "broker", "label": "MQTT Broker URL", "query": "localhost" }
  ]
 },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "description": "Logging of current temperature data",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jarvil-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature Logging",
   "type": "timeseries",
   "description": "Logging of recent temperature data",
   "gridPos": { "h": 8, "w": 15, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"jarvil-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature Control",
   "type": "text",
   "description": "Panel to control the library temperature",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n\n<style>\n    @import url('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700');\n\n    * {\n        box-sizing: border-box;\n        -webkit-user-select: none;\n        -moz-user-select: none;\n        -ms-user-select: none;\n        user-select: none;\n    }\n\n    html,\n    body {\n        margin: 0;\n        font-family: 'Open Sans', sans-serif;\n    }\n\n    .center_radius,\n    .thermostat,\n    .thermostat .bar,\n    .thermostat .center,\n    .thermostat .center .small {\n        top: 50%;\n        left: 50%;\n        transform: translate(-50%, -50%);\n        border-radius: 50%;\n    }\n\n    .thermostat {\n        width: 400px;\n        height: 400px;\n        background: #6d697f;\n        box-shadow: inset 0px -6px 1px 2px rgba(0, 0, 0, 0.35), 0px 7px 40px 11px rgba(84, 81, 97, 0.40);\n        transform: scale(0.5) translate(-30%, -40%);\n    }\n\n    .thermostat:hover .number {\n        opacity: 1;\n    }\n\n    .thermostat .shadow {\n        position: absolute;\n        top: 50%;\n        left: 50%;\n        transform: translate(-50%, -50%) rotateZ(10deg);\n        width: 25px;\n        height: 86%;\n        text-align: center;\n        transition: 0.7s ease;\n        animation: shadow 1.4s ease-out both;\n    }\n\n    .thermostat .shadow .shadow-cubeT {\n        position: absolute;\n        top: 0;\n        width: 25px;\n        height: 0px;\n        box-shadow: 0 0 45px 13px rgba(255, 158, 35, 0.5);\n    }\n\n    .thermostat .shadow .shadow-cubeH {\n        position: absolute;\n        top: 0;\n        width: 25px;\n        height: 0px;\n        box-shadow: 0 0 45px 13px rgba(35, 255, 171, 0.5);\n    }\n    \n    .thermostat .shadow .shadow-cubeB {\n        position: absolute;\n        top: 0;\n        width: 25px;\n        height: 0px;\n        box-shadow: 0 0 45px 13px rgba(255, 240, 35, 0.5);\n    }\n\n    .thermostat .number {\n        position: absolute;\n        top: 50%;\n        left: 50%;\n        transform: translate(-50%, -50%) rotateZ(10deg);\n        width: 40px;\n        height: 82%;\n        text-align: center;\n        transition: 0.7s ease;\n        opacity: 0;\n    }\n\n    .thermostat .number .ext {\n        font-size: 16px;\n        color: white;\n        font-weight: 1000;\n        text-shadow: 1px 3px 3px #302e38;\n    }\n\n    .thermostat .bar {\n        position: absolute;\n        width: 356px;\n        height: 356px;\n    }\n\n    .thermostat .bar .inner_bar {\n        position: absolute;\n        top: 50%;\n        left: 50%;\n        width: 344px;\n        height: 344px;\n        margin-left: -172px;\n        margin-top: -172px;\n        border-radius: 100%;\n        background-color: #6d697f;\n        z-index: 4;\n    }\n\n    .thermostat .bar .inner_bar:after {\n        content: '';\n        display: block;\n        position: absolute;\n        width: 0;\n        height: 0;\n        border-top: 70px solid transparent;\n        border-left: 70px solid transparent;\n        border-right: 70px solid transparent;\n        border-bottom: 150px solid #6d697f;\n        bottom: -7px;\n        left: 50%;\n        transform: translatex(-50%);\n    }\n\n    .thermostat .bar .hold {\n        position: absolute;\n        width: 100%;\n        height: 100%;\n        clip: rect(0px, 356px, 356px, 178px);\n        border-radius: 100%;\n        background-color: #3a3749;\n    }\n\n    .thermostat .bar .fill {\n        position: absolute;\n        width: 100%;\n        height: 100%;\n        border-radius: 100%;\n        clip: rect(0px, 178px, 356px, 0px);\n    }\n\n    .thermostat .bar .fill1T {\n        background: -webkit-linear-gradient(top, #ff4900 20%, #ff4900 100%);\n    }\n\n    .thermostat .bar .fill2T {\n        background: -webkit-linear-gradient(top, #ff4900 40%, #ff9e23 100%);\n    }\n\n    .thermostat .bar .fill1H {\n        background: -webkit-linear-gradient(top, #00ff80 20%, #00ff80 100%);\n    }\n\n    .thermostat .bar .fill2H {\n        background: -webkit-linear-gradient(top, #00ff80 40%, #7effb8 100%);\n    }\n\n    .thermostat .bar .fill1B {\n        background: -webkit-linear-gradient(top, #ffe600 20%, #ffe600 100%);\n    }\n\n    .thermostat .bar .fill2B {\n        background: -webkit-linear-gradient(top, #ffe600 40%, #fff27e 100%);\n    }\n\n    .thermostat .bar .right {\n        z-index: 3;\n        -webkit-transform: rotate(180deg);\n        -moz-transform: rotate(180deg);\n        transform: rotate(180deg);\n    }\n\n    .thermostat .bar .right .fill {\n        z-index: 3;\n        transform: rotate(180deg);\n        animation: right 1s linear both;\n        transition: transform 0.6s;\n    }\n\n    .thermostat .bar .left .fill {\n        z-index: 1;\n        animation: left 0.3s linear both;\n        animation-delay: 1s;\n        transition: transform 0.6s;\n    }\n\n    .thermostat .bar span {\n        width: 356px;\n        font-weight: 800;\n        position: absolute;\n        bottom: 0px;\n        text-align: center;\n        text-transform: uppercase;\n        font-size: 15px;\n        color: #2e2c3a;\n        z-index: 10;\n    }\n\n    .thermostat .center {\n        position: absolute;\n        width: 260px;\n        height: 260px;\n        background: #e3e4ed;\n        animation: bound-in 0.6s ease forwards;\n    }\n\n    .thermostat .center:hover .arrow {\n        opacity: 1;\n        transition: opacity 0.3s;\n    }\n\n    .thermostat .center:hover .minus {\n        left: 10px;\n        transition: left 0.3s ease-out;\n    }\n\n    .thermostat .center:hover .plus {\n        right: 45px;\n        transition: right 0.3s ease-out;\n    }\n\n    .thermostat .center span i {\n        position: absolute;\n        color: #b9b6c8;\n        font-size: 40px;\n        font-weight: 500;\n        line-height: 260px;\n    }\n\n    .thermostat .center .arrow {\n        opacity: 0;\n        transition: opacity 0.3s;\n        cursor: pointer;\n    }\n\n    .thermostat .center .minus {\n        position: absolute;\n        animation: arrow-left 1s forwards;\n    }\n\n    .thermostat .center .plus {\n        position: absolute;\n        animation: arrow-right 1s forwards;\n    }\n\n    .thermostat .center .small {\n        position: absolute;\n        width: 150px;\n        height: 150px;\n        background: #f8f9fa;\n        text-align: center;\n        animation: bound-in-small 0.6s ease forwards;\n    }\n\n    .thermostat .center .small .heat {\n        line-height: 150px;\n        font-size: 59px;\n        color: #57545f;\n        font-weight: 300;\n    }\n\n    .thermostat .center .small .heatT:after {\n        content: '°';\n        display: block;\n        position: absolute;\n        font-size: 40px;\n        top: -20px;\n        right: 30px;\n    }\n    .thermostat .center .small .heatB:after {\n        content: '%';\n    }\n\n    @-webkit-keyframes shadow {\n        0% {\n            transform: translate(-50%, -50%) rotate(-190deg);\n        }\n\n        100% {\n            transform: translate(-50%, -50%) rotate(10deg);\n        }\n    }\n\n    @-webkit-keyframes right {\n        0% {\n            transform: rotate(0deg);\n        }\n\n        100% {\n            transform: rotate(180deg);\n        }\n    }\n\n    @-webkit-keyframes left {\n        0% {\n            transform: rotate(0deg);\n        }\n\n        100% {\n            transform: rotate(10deg);\n        }\n    }\n\n    @-webkit-keyframes bound-in {\n        10% {\n            box-shadow: 0px 7px 30px 5px rgba(96, 93, 111, 0.25);\n            transform: translate(-50%, -50%) scale(0.8);\n        }\n\n        80% {\n            transform: translate(-50%, -50%) scale(1.03);\n        }\n\n        100% {\n            box-shadow: 0px 15px 35px 11px rgba(46, 44, 58, 0.60);\n            transform: translate(-50%, -50%) scale(1);\n        }\n    }\n\n    @-webkit-keyframes bound-in-small {\n        0% {\n            box-shadow: 0px 5px 10px 5px rgba(96, 93, 111, 0.19);\n            transform: translate(-50%, -50%) scale(0.8);\n        }\n\n        80% {\n            transform: translate(-50%, -50%) scale(1.03);\n        }\n\n        100% {\n            box-shadow: 0px 15px 35px 5px rgba(96, 93, 111, 0.30);\n            transform: translate(-50%, -50%) scale(1);\n        }\n    }\n\n    @-webkit-keyframes arrow-left {\n        0% {\n            left: 45px;\n            opacity: 0;\n        }\n\n        100% {\n            left: 10px;\n            opacity: 1;\n        }\n    }\n\n    @-webkit-keyframes arrow-right {\n        0% {\n            right: 75px;\n            opacity: 0;\n        }\n\n        100% {\n            right: 45px;\n            opacity: 1;\n        }\n    }\n</style>\n\n<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js\"></script>\n\n<script>\n    var gradiT = 19;\n    var gradiB = 19;\n    var gradiH = 19;\n    var max = 34;\n    var min = 2;\n\n    var mqtt;\n    var reconnectTimeout = 2000;\n    var host = `${broker}`;\n    var port = 9001;\n    var temperatureTopic = \"control-dashboard/0/value/temperature/setpoint\";\n    var brightnessTopic = \"control-dashboard/0/value/brightness/setpoint\";\n    var humidityTopic = \"control-dashboard/0/value/humidity/setpoint\";\n    var topicSelectIndex = 3;\n\n    function onConnect() {\n        console.log(\"Connected\");\n        mqtt.subscribe(temperatureTopic);\n        mqtt.subscribe(brightnessTopic);\n        mqtt.subscribe(humidityTopic);\n    }\n\n    function onFailure() {\n        console.log(\"Connection Attempt to Host \" + host + \" failed\");\n        setTimeout(mqttConnect, reconnectTimeout);\n    }\n\n    function onMessage(message) {\n        console.log(\"Message received: \" + message.payloadString);\n        var topicChar = message.destinationName.split(\"/\")[topicSelectIndex].charAt(0).toUpperCase();\n        var newValue = JSON.parse(message.payloadString)[\"set\"];\n        updateGr(newValue, topicChar);\n    }\n\n    function mqttMessage(value, topic) {\n        message = new Paho.MQTT.Message(`{\"set\": ${value}}`);\n        message.destinationName = topic;\n        message.qos = 1;\n        message.retained = true;\n        mqtt.send(message);\n        console.log(\"MQTT message sent\");\n    }\n\n    function mqttConnect() {\n        console.log(\"connecting to \" + host + \":\" + port);\n        mqtt = new Paho.MQTT.Client(host, port, \"clientjs\");\n        var options = {\n            timeout: 3,\n            onSuccess: onConnect,\n            onFailure: onFailure,\n        };\n        mqtt.onMessageArrived = onMessage\n        mqtt.connect(options);\n    }\n\n    function updateGr(newValue, topicChar) {\n        console.log(\"Old newValue: \" + newValue);\n        if (topicChar == \"B\" || topicChar == \"H\") newValue = Math.round(newValue * 34);\n        console.log(\"New newValue: \" + newValue);\n        var gradi;\n        if (topicChar == \"T\") gradi = gradiT;\n        if (topicChar == \"B\") gradi = gradiB;\n        if (topicChar == \"H\") gradi = gradiH;\n        console.log(`Old value: ${gradi}, new value: ${newValue}`);\n        if (newValue < gradi) {\n            if (newValue >= 18) {\n                $(`.fill1${topicChar}`).css(\"transform\", \"rotate(\" + (newValue - 18) * 10 + \"deg)\").css(\"transition-delay\", \"0s\");\n            } else if (newValue == 17) {\n                $(`.fill2${topicChar}`).css(\"transform\", \"rotate(\" + newValue * 10 + \"deg)\").css(\"transition-delay\", \"0s\");\n            } else {\n                $(`.fill2${topicChar}`).css(\"transform\", \"rotate(\" + newValue * 10 + \"deg)\").css(\"transition-delay\", \"0s\");\n            }\n        }\n        else {\n            if (newValue > 19) {\n                $(`.fill1${topicChar}`).css(\"transform\", \"rotate(\" + (newValue - 18) * 10 + \"deg)\").css(\"transition-delay\", \"0s\");\n            } else if (newValue == 19) {\n                $(`.fill1${topicChar}`).css(\"transform\", \"rotate(\" + (newValue - 18) * 10 + \"deg)\").css(\"transition-delay\", \"0s\");\n            } else {\n                $(`.fill2${topicChar}`).css(\"transform\", \"rotate(\" + newValue * 10 + \"deg)\").css(\"transition-delay\", \"0s\");\n            }\n        }\n        gradi = newValue;\n        if (topicChar == \"T\") gradiT = newValue;\n        if (topicChar == \"B\") gradiB = newValue;\n        if (topicChar == \"H\") gradiH = newValue;\n        $(`.number${topicChar}`).css(\"transform\", \"translate(-50%, -50%) rotate(\" + (-180 + gradi * 10) + \"deg)\");\n        $(`.shadow${topicChar}`).css(\"transform\", \"translate(-50%, -50%) rotate(\" + (-180 + gradi * 10) + \"deg)\");\n        $(`.fill${topicChar}`).css(\"animation\", \"none\");\n        $(`.shadow${topicChar}`).css(\"animation\", \"none\");\n        console.log(\"Old gradi: \" + gradi);\n        if (topicChar == \"B\") gradi = Math.round(gradi / 34 * 100);\n        if (topicChar == \"H\") gradi = (gradi / 34).toFixed(2);\n        console.log(\"New gradi: \" + gradi);\n        $(`.heat${topicChar}`).text(\"\" + gradi);\n        $(`.ext${topicChar}`).text(\"\" + gradi);\n    }\n\n\n    $(\".minusT\").mousedown(function () {\n        console.log(\"Temperature minus\")\n        if (gradiT > min) {\n            mqttMessage(gradiT - 1, temperatureTopic)\n        }\n    });\n\n    $(\".plusT\").mousedown(function () {\n        console.log(\"Temperature plus\")\n        if (gradiT < max) {\n            mqttMessage(gradiT + 1, temperatureTopic)\n        }\n    });\n\n    setTimeout(mqttConnect, 1000);\n</script>\n\n<div class=\"thermostat\">\n    <div class=\"bar\">\n        <div class=\"inner_bar\"></div>\n        <div class='hold left'>\n            <div class='fill fillT fill1T'></div>\n        </div>\n        <div class='hold right'>\n            <div class='fill fillT fill2T'></div>\n        </div>\n        <span>Heating</span>\n    </div>\n    <div class=\"shadow shadowT\">\n        <div class=\"shadow-cubeT\"></div>\n    </div>\n    <div class=\"number numberT\">\n        <span class=\"ext extT\">...</span>\n    </div>\n    <div class=\"center\">\n        <span class=\"arrow minus minusT\"><i class=\"material-icons\">keyboard_arrow_left</i></span>\n        <span class=\"arrow plus plusT\"><i class=\"material-icons\">keyboard_arrow_right</i></span>\n        <div class=\"small\">\n            <span class=\"heat heatT\">...</span>\n        </div>\n    </div>\n</div>"
   }
  },
  {
   "title": "Current Brightness",
   "type": "gauge",
   "description": "Logging of current brightness data",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jarvil-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"brightness\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Brightness Logging",
   "type": "timeseries",
   "description": "Logging of recent brightness data",
   "gridPos": { "h": 8, "w": 15, "x": 4, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"jarvil-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"brightness\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Brightness Control",
   "type": "text",
   "description": "Panel to control the library light",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": {
    "content": "<script>\n    $(\".minusB\").mousedown(function () {\n        console.log(\"Brightness minus\")\n        if (gradiB > min) {\n            console.log(\"Pushing new calculated value: \" + (gradiB / 34 - 0.01).toFixed(2))\n            mqttMessage(((gradiB - 1) / 34).toFixed(2), brightnessTopic)\n        }\n    });\n\n    $(\".plusB\").mousedown(function () {\n        console.log(\"Brightness plus\")\n        if (gradiB < max) {\n            console.log(\"Pushing new calculated value: \" + (gradiB / 34 + 0.01).toFixed(2))\n            mqttMessage(((gradiB + 1) / 34).toFixed(2), brightnessTopic)\n        }\n    });\n\n</script>\n<div class=\"thermostat\">\n    <div class=\"bar\">\n        <div class=\"inner_bar\"></div>\n        <div class='hold left'>\n            <div class='fill fillB fill1B'></div>\n        </div>\n        <div class='hold right'>\n            <div class='fill fillB fill2B'></div>\n        </div>\n        <span>Brightness</span>\n    </div>\n    <div class=\"shadow shadowB\">\n        <div class=\"shadow-cubeB\"></div>\n    </div>\n    <div class=\"number numberB\">\n        <span class=\"ext extB\">...</span>\n    </div>\n    <div class=\"center\">\n        <span class=\"arrow minus minusB\"><i class=\"material-icons\">keyboard_arrow_left</i></span>\n        <span class=\"arrow plus plusB\"><i class=\"material-icons\">keyboard_arrow_right</i></span>\n        <div class=\"small\">\n            <span class=\"heat heatB\">...</span>\n        </div>\n    </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "description": "Logging of current humidity data",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jarvil-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity Logging",
   "type": "timeseries",
   "description": "Logging of recent humidity data",
   "gridPos": { "h": 8, "w": 15, "x": 4, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"jarvil-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate-service_sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity Control",
   "type": "text",
   "description": "Panel to control the library humidity",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "options": {
    "content": "<script>\n    $(\".minusH\").mousedown(function () {\n        console.log(\"Humidity minus\")\n        if (gradiH > min) {\n            console.log(\"Pushing new calculated value: \" + (gradiH / 34 - 0.01).toFixed(2))\n            mqttMessage(((gradiH - 1) / 34).toFixed(2), humidityTopic)\n        }\n    });\n\n    $(\".plusH\").mousedown(function () {\n        console.log(\"Humidity plus\")\n        if (gradiH < max) {\n            console.log(\"Pushing new calculated value: \" + (gradiH / 34 + 0.01).toFixed(2))\n            mqttMessage(((gradiH + 1) / 34).toFixed(2), humidityTopic)\n        }\n    });\n\n</script>\n<div class=\"thermostat\">\n    <div class=\"bar\">\n        <div class=\"inner_bar\"></div>\n        <div class='hold left'>\n            <div class='fill fillH fill1H'></div>\n        </div>\n        <div class='hold right'>\n            <div class='fill fillH fill2H'></div>\n        </div>\n        <span>Humidify</span>\n    </div>\n    <div class=\"shadow shadowH\">\n        <div class=\"shadow-cubeH\"></div>\n    </div>\n    <div class=\"number numberH\">\n        <span class=\"ext extH\">...</span>\n    </div>\n    <div class=\"center\">\n        <span class=\"arrow minus minusH\"><i class=\"material-icons\">keyboard_arrow_left</i></span>\n        <span class=\"arrow plus plusH\"><i class=\"material-icons\">keyboard_arrow_right</i></span>\n        <div class=\"small\">\n            <span class=\"heat heatH\">...</span>\n        </div>\n    </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time Slot bookings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"jarvil-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"time-slot-booking_booking\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  }
 ]
}