name: BalenaCloud Push

on:
  push:
    branches:
      - main

jobs:
  balena-push-pi-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: canastro/copy-action@0.0.2
      with:
        source: "docker/pi-1/docker-compose.yml"
        target: "docker-compose.yml"
    - uses: amingilani/push-to-balenacloud@v1.0.1
      with:
        api-token: ${{ secrets.BALENA_API_TOKEN }}
        application-name: "jarvil-pi-1"
    
  balena-push-pi-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: canastro/copy-action@0.0.2
      with:
        source: "docker/pi-2/docker-compose.yml"
        target: "docker-compose.yml"
    - uses: amingilani/push-to-balenacloud@v1.0.1
      with:
        api-token: ${{ secrets.BALENA_API_TOKEN }}
        application-name: "jarvil-pi-2"
    
  balena-push-pi-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: canastro/copy-action@0.0.2
      with:
        source: "docker/pi-3/docker-compose.yml"
        target: "docker-compose.yml"
    - uses: amingilani/push-to-balenacloud@v1.0.1
      with:
        api-token: ${{ secrets.BALENA_API_TOKEN }}
        application-name: "jarvil-pi-3"