name: BalenaCloud Push Pi-2

on:
  push:
    branches:
      - main

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: amingilani/push-to-balenacloud@v1.0.1
      with:
        api-token: ${{ secrets.BALENA_API_TOKEN }}
        application-name: "jarvil-pi-2"
        application-path: "./docker/development/pi-2"